### ISSUE TITLE
can't run mvn clean package successfully  in EM/demos dir , any suggestions ?

### ISSUE THREAD

**Issue by AndyWu2015** [azzazzel/EM#1]

**Comment by milendyankov** [comment]
Hi, 
sorry for late response, it seams notifications for issues does not work for me. Can you try again and if still have problems provide the output. 

Also please note that in `master` branch, demos depend on not yet released version `0.2.0-SNAPSHOT`. Before you can use them, you need to:
 - run `mvn clean install` in the main folder, which will build and install locally EM and it's dependencies
 - run `mvn clean install` in `contractors` folder  which will build and install locally the OOTB contractors

**Comment by azzazzel** [comment]
Hi, 
sorry for late response, it seams notifications for issues does not work for me. Can you try again and if still have problems provide the output. 

Also please note that in `master` branch, demos depend on not yet released version `0.2.0-SNAPSHOT`. Before you can use them, you need to:
 - run `mvn clean install` in the main folder, which will build and install locally EM and it's dependencies
 - run `mvn clean install` in `contractors` folder  which will build and install locally the OOTB contractors

**Comment by azzazzel** [comment]
I'm closing this issue. Please reopen if you still experience the problem.
